### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by sebastiantimwagner** [ec-jrc/GHS-S2Net#2]
Dear authors,

what are the Python version and Python package versions that have been tested with the codebase? I'm using the following setup to execute `code/GHS_S2_run_prediction.py`:
`Python 3.6.9` on `Ubuntu 18.04`
and the pip package versions:
```
tensorflow==1.15
Keras==2.3.1
GDAL==3.04
```
I'm getting the following error when running `code/GHS_S2_run_prediction.py`:
```
XXX lineno: 187, opcode: 160
Traceback (most recent call last):
  File "GHS_S2_run_prediction.py", line 74, in <module>
    model = load_model('../Pretrained_models/MODEL_CNN_32T' + '.h5')
  File "/persistent/swagner/GHS-S2Net/env/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/persistent/swagner/GHS-S2Net/env/lib/python3.6/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/persistent/swagner/GHS-S2Net/env/lib/python3.6/site-packages/keras/engine/saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/persistent/swagner/GHS-S2Net/env/lib/python3.6/site-packages/keras/engine/saving.py", line 627, in model_from_config
    /persistent/swagner/GHS-S2Net/env/lib/python3.6/site-packages/tensorflow/include/tensorflow/c    return deserialize(config, custom_objects=custom_objects)
  File "/persistent/swagner/GHS-S2Net/env/lib/python3.6/site-packages/keras/layers/__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "/persistent/swagner/GHS-S2Net/env/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "/persistent/swagner/GHS-S2Net/env/lib/python3.6/site-packages/keras/engine/network.py", line 1075, in from_config
    process_node(layer, node_data)
  File "/persistent/swagner/GHS-S2Net/env/lib/python3.6/site-packages/keras/engine/network.py", line 1025, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/persistent/swagner/GHS-S2Net/env/lib/python3.6/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/persistent/swagner/GHS-S2Net/env/lib/python3.6/site-packages/keras/layers/core.py", line 716, in call
    return self.function(inputs, **arguments)
  File "/opt/venv/lib/python3.7/site-packages/keras/utils/multi_gpu_utils.py", line 187, in get_slice
SystemError: unknown opcode
```

**Comment by misterspook** [comment]
Dear Sebastian,

these are the versions of the libraries:
tensorflow-gpu==2.0.0
Keras==2.3.1
GDAL==2.4.2

I hope this helps.
We plan soon to add the requirements file.

**Comment by sebastiantimwagner** [comment]
Hi,

thanks for the quick reply. I've reiterated the execution after changing my local package versions and still get the same error. 

Which Python version did you use for testing?

Thanks,
Sebastian

**Comment by misterspook** [comment]
Hello,

it was this one:
python 3.7.4
and ubuntu 18.04.5

**Comment by misterspook** [comment]
added requirements.txt

**Comment by manapshymyr-OB** [comment]
> Hi,
> 
> thanks for the quick reply. I've reiterated the execution after changing my local package versions and still get the same error.
> 
> Which Python version did you use for testing?
> 
> Thanks,
> Sebastian

Were you able to run the prediction?
